### PR TITLE
Add `o-editorial-layout-wrapper`.

### PR DESCRIPTION
**Pull request by notlee**
This replaces [o-typography-wrapper](https://github.com/Financial-Times/o-typography/tree/v5.12.0)

### CODE REVIEW

**Comment by notlee** [comment]
This is not a breaking despite `o-quote` being a new dependency because they share implicit dependencies and `o-editorial-layout` is not compatible with other versions of `o-quote` already

**Comment by origamiserviceuser** [comment]
o-editorial-layout bundle size difference from 1.0.0 to df81f8d6ce53c7c89c4ac27fa52154a50ed0a521
css: 9.62kb increase (1.17kb/gzip)

**Comment by origamiserviceuser** [comment]
o-editorial-layout bundle size difference from 1.0.0 to 8dc6fd5f19ffd5d5902ba302b83c3ed54474916d
css: 9.62kb increase (1.17kb/gzip)

**Comment by origamiserviceuser** [comment]
o-editorial-layout bundle size difference from 1.0.0 to 2ab999851a492bcd9f4c2e85ab557db72a2b849e
css: 9.62kb increase (1.17kb/gzip)

**Review by apaleslimghost — APPROVED** [review]

**Review by chee — APPROVED** [review]
Let's release a beta and test it in the context of amp ^_^

**Pull request merged**
