### PR TITLE
Use new editorial quote style.

### PR DESCRIPTION
**Pull request by notlee**
Designed by Josh in the Content Innovation Team.
Background: https://github.com/Financial-Times/o-quote/issues/51

before
Screenshot 2020-04-24 at 11 02 26

after
Screenshot 2020-04-24 at 11 02 03

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-editorial-layout bundle size difference from 1.1.1 to 7c466f3543d973e29e145491d1404b4c45c83877
css, master: 0.75kb increase (0.26kb/gzip)

**Review by JakeChampion — APPROVED** [review]
Yes!

**Comment by JakeChampion** [comment]
:tada: This PR is included in version v1.1.2 :tada:

**Comment by origamiserviceuser** [comment]
o-editorial-layout bundle size difference from 1.1.1 to 4d3e0a556359b168235be1fc54574d25d4d28033
css, master: 0.75kb increase (0.26kb/gzip)

**Pull request merged**
